"""Phase 4 gating diagnostic: verify token sequence -> audio waveform round-trip.

GRPO's reward function operates on completion *strings* (generated by the LM):
each completion is a string of OuteTTS audio tokens that we need to decode back
to a waveform so we can score it with Whisper / UTMOS / ECAPA.

This script picks one existing audio file, runs it through the full
audio -> tokens -> string -> audio pipeline, and reports per-step shapes so we
can confirm each method does what we think it does. If anything is wrong, this
fails cheaply (<1 min) before we write the GRPO training script around it.

Steps:
    1. Load an existing audio file.
    2. create_speaker -> Speaker dict.
    3. get_training_prompt(speaker) -> full LM string (text + codes).
    4. Tokenize the audio-tokens portion -> integer token IDs.
    5. extract_audio_from_tokens(ids) -> DAC code grid.
    6. DAC decode -> waveform.
    7. Save reconstructed audio to disk for ear-check.

If step 5/6 succeed and the output WAV is recognizable as the original
sentence (even if a touch lossier), the GRPO reward path is feasible.
"""
from __future__ import annotations

import inspect
import logging
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("rt")

DEFAULT_AUDIO = Path("data/generated/p0000_t0.wav")


def main() -> int:
    import outetts
    from transformers import AutoTokenizer

    audio_path = DEFAULT_AUDIO if DEFAULT_AUDIO.exists() else next(Path("data/generated").glob("p*_t0.wav"))
    logger.info("input audio: %s", audio_path)

    iface = outetts.Interface(config=outetts.ModelConfig.auto_config(
        model=outetts.Models.VERSION_1_0_SIZE_1B,
        backend=outetts.Backend.HF,
    ))
    tokenizer = AutoTokenizer.from_pretrained("OuteAI/Llama-OuteTTS-1.0-1B")

    # ----- 1. create_speaker -----
    src_audio, src_sr = sf.read(str(audio_path), always_2d=False)
    if src_audio.ndim > 1:
        src_audio = src_audio.mean(axis=1)
    print(f"\n[1] source audio: sr={src_sr}, len={len(src_audio)} ({len(src_audio)/src_sr:.2f}s)")

    # We need a target text. For round-trip purposes, Whisper's own transcription is fine.
    spk = iface.create_speaker(audio_path=str(audio_path))
    print(f"[2] speaker keys: {list(spk.keys())}")
    print(f"    speaker text: {spk.get('text', '<none>')[:120]!r}")
    print(f"    words aligned: {len(spk.get('words', []))}")

    # ----- 3. get_training_prompt -----
    full = iface.prompt_processor.get_training_prompt(spk)
    print(f"\n[3] full training prompt: {len(full)} chars")
    print(f"    first 200: {full[:200]!r}")
    print(f"    last 200:  {full[-200:]!r}")

    # ----- 4. tokenize -----
    token_ids = tokenizer.encode(full, add_special_tokens=False)
    print(f"\n[4] token IDs: len={len(token_ids)}")
    print(f"    first 20: {token_ids[:20]}")

    # ----- 5. extract_audio_from_tokens -----
    extract_sig = inspect.signature(iface.prompt_processor.extract_audio_from_tokens)
    print(f"\n[5] extract_audio_from_tokens signature: {extract_sig}")
    try:
        codes = iface.prompt_processor.extract_audio_from_tokens(token_ids)
        print(f"    return type: {type(codes).__name__}")
        if hasattr(codes, 'shape'):
            print(f"    shape: {tuple(codes.shape)}, dtype: {codes.dtype}")
        elif isinstance(codes, (list, tuple)):
            print(f"    len: {len(codes)}, [0] type: {type(codes[0]).__name__ if codes else 'empty'}")
            if codes and hasattr(codes[0], 'shape'):
                print(f"    [0] shape: {tuple(codes[0].shape)}")
        else:
            print(f"    repr: {repr(codes)[:200]}")
    except Exception as e:
        print(f"    FAILED: {type(e).__name__}: {e}")
        return 1

    # ----- 6. decode codes -> waveform -----
    print(f"\n[6] decoding codes back to waveform...")

    # extract_audio_from_tokens returns list[list[int]] (one inner list per DAC codebook).
    # The codec expects an int64 tensor shaped (B=1, n_codebooks=2, T) on the codec's device.
    codes_t = torch.tensor(codes, dtype=torch.long).unsqueeze(0).to(iface.audio_codec.device)
    print(f"    codes tensor shape: {tuple(codes_t.shape)}, dtype: {codes_t.dtype}, device: {codes_t.device}")

    decoded_audio = None
    # Prefer the low-level codec.decode — it's what produced the codes via encode in Phase 2.
    try:
        decoded_audio = iface.audio_codec.decode(codes_t)
        if hasattr(decoded_audio, 'shape'):
            print(f"    audio_codec.decode -> shape {tuple(decoded_audio.shape)}, dtype {decoded_audio.dtype}")
        elif hasattr(decoded_audio, 'audio'):
            print(f"    audio_codec.decode -> object with .audio shape {tuple(decoded_audio.audio.shape)}")
        else:
            print(f"    audio_codec.decode -> type {type(decoded_audio).__name__}: {repr(decoded_audio)[:200]}")
    except Exception as e:
        print(f"    audio_codec.decode FAILED: {type(e).__name__}: {e}")
        # Fall back: try iface.get_audio with the tensor (may still object).
        try:
            print(f"    falling back to iface.get_audio(codes_t)")
            decoded_audio = iface.get_audio(codes_t)
            if hasattr(decoded_audio, 'shape'):
                print(f"    iface.get_audio -> shape {tuple(decoded_audio.shape)}, dtype {decoded_audio.dtype}")
        except Exception as e2:
            print(f"    iface.get_audio also FAILED: {type(e2).__name__}: {e2}")
            return 2

    # ----- 7. save reconstructed audio -----
    # Normalize whatever we got to a 1-D float numpy array
    arr = decoded_audio
    if hasattr(arr, 'audio'):
        arr = arr.audio
    if hasattr(arr, 'cpu'):
        arr = arr.cpu().numpy()
    arr = np.asarray(arr).squeeze()
    if arr.ndim > 1:
        arr = arr.mean(axis=0) if arr.shape[0] < arr.shape[-1] else arr.mean(axis=-1)

    out_sr = getattr(iface.audio_codec, 'sr', 24000)
    out_path = Path("data/generated/roundtrip_test.wav")
    sf.write(str(out_path), arr.astype(np.float32), int(out_sr))
    print(f"\n[7] wrote reconstructed audio: {out_path} (sr={out_sr}, len={len(arr)})")
    print(f"    ear-check: scp this back to your Mac and compare to {audio_path}")

    print("\nPASS — token round-trip works. GRPO reward path is feasible.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
